#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
